<template>
  <div class="privacy-policy">
    <p>
    Edible Interfaces is a suite of public utilities whose use require no personal information.
    We do not store any user data at all. 
    Any data generated by an Edible Interfaces app is stored in your browser cache or by a 3rd-party cloud provider such as Google or Dropbox.</h1>
    </p>
  </div>
</template>

<style lang="scss" scoped>

  @import "@/assets/scss/colors.scss";

  .privacy-policy {
    height: '100%';
  }

</style>

<script>
  export default { 
    name: 'PrivacyPolicy' 
  }
</script>


